return {
	[ "and" ] = "TK_AND",
	[ "break" ] = "TK_BREAK",
	[ "do" ] = "TK_DO",
	[ "else" ] = "TK_ELSE",
	[ "elseif" ] = "TK_ELSEIF",
	[ "end" ] = "TK_END",
	[ "for" ] = "TK_FOR",
	[ "function" ] = "TK_FUNCTION",
	[ "if" ] = "TK_IF",
	[ "in" ] = "TK_IN",
	[ "local" ] = "TK_LOCAL",
	[ "not" ] = "TK_NOT",
	[ "while" ] = "TK_WHILE",
	[ "repeat" ] = "TK_REPEAT",
	[ "return" ] = "TK_RETURN",
	[ "then" ] = "TK_THEN",
	[ "self" ] = "TK_SELF",
	[ "until" ] = "TK_UNTIL",
	[ "or" ] = "TK_OR",
}